### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by alex4200**
Adding Acknowledgment and copyright

### CODE REVIEW

**Review by tristan0x — APPROVED** [review]

**Comment by alex4200** [comment]
@tristan0x Can you check the error in the tests please?

**Comment by tristan0x** [comment]
This new error is way more serious. I will try to take a look at it this afternoon

**Comment by alexsavulescu** [comment]
This PR doesn't need the CI to pass, will merge as is and open a ticket for the brew test failure.

**Comment by alexsavulescu** [comment]
@tristan0x [2a449a5](https://github.com/BlueBrain/homebrew-tap/pull/9/commits/2a449a54f4e0a54fd013674d652a922dd9bf47ab) was already done in #8 , I wonder if that PR should be finalized?

**Comment by tristan0x** [comment]
> @tristan0x [2a449a5](https://github.com/BlueBrain/homebrew-tap/pull/9/commits/2a449a54f4e0a54fd013674d652a922dd9bf47ab) was already done in #8 , I wonder if that PR should be finalized?

I wanted to avoid to both change PETSc version and update the recipe to ease troubleshooting in case of issue, but that's fine. Thanks for updating #8

**Comment by alexsavulescu** [comment]
> > @tristan0x [2a449a5](https://github.com/BlueBrain/homebrew-tap/pull/9/commits/2a449a54f4e0a54fd013674d652a922dd9bf47ab) was already done in #8 , I wonder if that PR should be finalized?
> 
> I wanted to avoid to both change PETSc version and update the recipe to ease troubleshooting in case of issue, but that's fine. Thanks for updating #8

How about we simply update the recipe in another PR?

**Pull request merged**
